name = "bless-crypto-live-price-tracker"
version = "1.0.0"
type = "text"
production_host = "magenta-ocelot-thea-5wfwuhf4.bls.dev"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "bless-crypto-live-price-tracker_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "bless-crypto-live-price-tracker.wasm"
command = "npm run build:release"

[[deployments]]
name = "blessnet"
description = ""
cid = "bafybeidn3tiigspszolsstpngm5yaw47ojx3gx4oujz6dyldntu353plqi"
created = "2025-09-03T18:17:22.699Z"

  [deployments.runtime]
  url = "blessnet.tar.gz"
  checksum = "4fd7d2a9d61aa736415c63be0afb7a834782c47afbdfd8e757db18ccc1d51c95"
